DROP TABLE ALMACEN;
DROP TABLE AREA;
DROP TABLE CAPACIDADES;
DROP TABLE CAPACIDADES_MENU;
DROP TABLE CAPACIDADES_MENU_ITEM;
DROP TABLE CARGO;
DROP TABLE DETALLE_MEDICAMENTO;
DROP TABLE ESPECIALIDAD;
DROP TABLE HORARIO;
DROP TABLE ITEM;
DROP TABLE MEDICAMENTO;
DROP TABLE MENU;
DROP TABLE MENU_ITEM;
DROP TABLE PACIENTE;
DROP TABLE PACIENTE_PADECIM;
DROP TABLE PADECIMIENTO;
DROP TABLE PERSONAL;
DROP TABLE PERSONAL_ESPECIALIDAD;
DROP TABLE RESPONSABLE_TURNO;
DROP TABLE TIPO_USUARIO;
DROP TABLE TURNO;
DROP TABLE USUARIO;
DROP TABLE USUARIO_CAPACIDAD;



CREATE TABLE ITEM (
                ITEM_ID INTEGER NOT NULL,
                ETIQUETA VARCHAR(60) NOT NULL,
                LOGO VARCHAR(80),
                DESCRIPCION VARCHAR(256) NOT NULL,
                CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID)
);


CREATE TABLE MENU (
                MENU_ID INTEGER NOT NULL,
                MENU_PADRE INTEGER,
                ETIQUETA VARCHAR(60),
                LOGO VARCHAR(80),
                DESCRIPCION VARCHAR(256) NOT NULL,
                CONSTRAINT MENU_PK PRIMARY KEY (MENU_ID)
);


CREATE TABLE MENU_ITEM (
                MENU_ID INTEGER NOT NULL,
                ITEM_ID INTEGER NOT NULL
);


CREATE TABLE TIPO_USUARIO (
                TIU_ID INTEGER NOT NULL,
                TIU_NOMBRE VARCHAR(60) NOT NULL,
                TIU_DESCRIP VARCHAR(60) NOT NULL,
                TIU_ESTADO VARCHAR(1) NOT NULL,
                CONSTRAINT TIPO_USUARIO_PK PRIMARY KEY (TIU_ID)
);


CREATE TABLE USUARIO (
                USU_ID INTEGER NOT NULL,
                TIU_ID INTEGER NOT NULL,
                USU_LOGIN VARCHAR(256) NOT NULL,
                USU_CONTRASENA VARCHAR(512) NOT NULL,
                USU_ESTADO VARCHAR(1) NOT NULL,
                USU_FECHA_ALTA DATE NOT NULL,
                USU_FECHA_VENCIMIENTO DATE NOT NULL,
                USU_CORREO VARCHAR(120) NOT NULL,
                CONSTRAINT USUARIO_PK PRIMARY KEY (USU_ID)
);


CREATE TABLE PERSONAL (
                PERS_ID INTEGER NOT NULL,
                USU_ID INTEGER,
                PERS_CEDULA VARCHAR(25) NOT NULL,
                PERS_NOMBRE VARCHAR(60) NOT NULL,
                PERS_APELLIDO_PAT VARCHAR(60) NOT NULL,
                PERS_APELLIDO_MAT VARCHAR(60) NOT NULL,
                PERS_FECHAN DATE NOT NULL,
                PERS_CELULAR VARCHAR(25) NOT NULL,
                PERS_CORREO VARCHAR(100) NOT NULL,
                PERS_TURNO VARCHAR(30) NOT NULL,
                PERS_SEXO VARCHAR(25) NOT NULL,
                PERS_ESTADO VARCHAR(1) NOT NULL,
                CONSTRAINT PERSONAL_PK PRIMARY KEY (PERS_ID)
);


CREATE TABLE PADECIMIENTO (
                PAD_ID INTEGER NOT NULL,
                PAD_NOMBRE VARCHAR(100) NOT NULL,
                PAD_ESTADO VARCHAR(1) NOT NULL,
                CONSTRAINT PADECIMIENTO_PK PRIMARY KEY (PAD_ID)
);


CREATE TABLE PACIENTE (
                PAC_ID INTEGER NOT NULL,
                USU_ID INTEGER,
                PAC_NOMBRE VARCHAR(60) NOT NULL,
                PAC_APELLIDO_PATERNO VARCHAR(60) NOT NULL,
                PAC_APELLIDO_MATERNO VARCHAR(60) NOT NULL,
                PAC_FECHAN DATE NOT NULL,
                PAC_SEXO VARCHAR(15) NOT NULL,
                PAC_DOMICILIO VARCHAR(100) NOT NULL,
                PAC_CELULAR VARCHAR(25) NOT NULL,
                PAC_CORREO VARCHAR(50) NOT NULL,
                PAC_OCUPAC VARCHAR(100) NOT NULL,
                PAC_TIPO VARCHAR(60) NOT NULL,
                PAC_ESTADO VARCHAR(1) NOT NULL,
                CONSTRAINT PACIENTE_PK PRIMARY KEY (PAC_ID)
);


CREATE TABLE TURNO (
                TUR_ID INTEGER NOT NULL,
                PERS_ID INTEGER NOT NULL,
                PAC_ID INTEGER NOT NULL,
                TUR_FECHA DATE NOT NULL,
                TUR_CITA VARCHAR(120) NOT NULL,
                TUR_ESTADO VARCHAR(1) NOT NULL,
                CONSTRAINT TURNO_PK PRIMARY KEY (TUR_ID)
);


CREATE TABLE PACIENTE_PADECIM (
                PAP_ID INTEGER NOT NULL,
                PAD_ID INTEGER NOT NULL,
                PAC_ID INTEGER NOT NULL,
                CONSTRAINT PACIENTE_PADECIM_PK PRIMARY KEY (PAP_ID)
);


CREATE TABLE MEDICAMENTO (
                MED_ID INTEGER NOT NULL,
                MED_NOMBRE_COMERCIAL VARCHAR(60) NOT NULL,
                MED_ELABORADO_EN VARCHAR(60) NOT NULL,
                MED_NOMBRE_GENERICO VARCHAR(60) NOT NULL,
                MED_NOMBRE_GENERICO_1 VARCHAR(10) NOT NULL,
                MED_FARMACEUTICA VARCHAR(60) NOT NULL,
                MED_CONDICION_VENTA VARCHAR(60) NOT NULL,
                MED_ESTADO VARCHAR(1) NOT NULL,
                CONSTRAINT MEDICAMENTO_PK PRIMARY KEY (MED_ID)
);


CREATE TABLE HORARIO (
                HOR_ID INTEGER NOT NULL,
                HOR_HR_INI TIMESTAMP NOT NULL,
                HOR_HR_FIN TIMESTAMP NOT NULL,
                HOR_LUN TIMESTAMP NOT NULL,
                HOR_MAR TIMESTAMP NOT NULL,
                HOR_MIE TIMESTAMP NOT NULL,
                HOR_JUE TIMESTAMP NOT NULL,
                HOR_VIE TIMESTAMP NOT NULL,
                HOR_ESTADO VARCHAR(1) DEFAULT A NOT NULL,
                CONSTRAINT HORARIO_PK PRIMARY KEY (HOR_ID)
);


CREATE TABLE ESPECIALIDAD (
                ESP_ID INTEGER NOT NULL,
                ESP_NOMBRE VARCHAR(100) NOT NULL,
                ESP_ESTADO VARCHAR(1) DEFAULT A NOT NULL,
                CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY (ESP_ID)
);


CREATE TABLE PERSONAL_ESPECIALIDAD (
                PEE_ID INTEGER NOT NULL,
                PERS_ID INTEGER NOT NULL,
                ESP_ID INTEGER NOT NULL,
                HOR_ID INTEGER NOT NULL,
                CONSTRAINT PERSONAL_ESPECIALIDAD_PK PRIMARY KEY (PEE_ID)
);


CREATE TABLE CARGO (
                CAR_ID INTEGER NOT NULL,
                CAR_NOMBRE VARCHAR(100) NOT NULL,
                CAR_ESTADO VARCHAR(1) NOT NULL,
                CONSTRAINT CARGO_PK PRIMARY KEY (CAR_ID)
);


CREATE TABLE CAPACIDADES (
                CAP_ID INTEGER NOT NULL,
                CAP_NOMBRE VARCHAR(100) NOT NULL,
                CAP_DESCRIPCION VARCHAR(150) NOT NULL,
                CAP_ESTADO VARCHAR(1) DEFAULT A NOT NULL,
                CONSTRAINT CAPACIDADES_PK PRIMARY KEY (CAP_ID)
);


CREATE TABLE CAPACIDADES_MENU_ITEM (
                CAP_ID INTEGER NOT NULL,
                ITEM_ID INTEGER NOT NULL
);


CREATE TABLE CAPACIDADES_MENU (
                CAP_ID INTEGER NOT NULL,
                MENU_ID INTEGER NOT NULL
);


CREATE TABLE USUARIO_CAPACIDAD (
                CAP_ID INTEGER NOT NULL,
                TIU_ID INTEGER NOT NULL
);


CREATE TABLE AREA (
                AREA_ID INTEGER NOT NULL,
                ARE_NOMBRE VARCHAR(100) NOT NULL,
                ARE_ESTADO VARCHAR(1) DEFAULT A NOT NULL,
                CONSTRAINT AREA_PK PRIMARY KEY (AREA_ID)
);


CREATE TABLE RESPONSABLE_TURNO (
                RET_ID INTEGER NOT NULL,
                CAR_ID INTEGER NOT NULL,
                AREA_ID INTEGER NOT NULL,
                RET_NOMBRE VARCHAR(120) NOT NULL,
                RET_APELLIDO_PAT VARCHAR(120) NOT NULL,
                RET_APELLIDO_MAT VARCHAR(120) NOT NULL,
                RET_TITULO VARCHAR(120) NOT NULL,
                RET_CELULAR VARCHAR(120) NOT NULL,
                RET_CORREO VARCHAR(120) NOT NULL,
                RET_ESTADO VARCHAR(1) NOT NULL,
                PERS_ID INTEGER NOT NULL,
                CONSTRAINT RESPONSABLE_TURNO_PK PRIMARY KEY (RET_ID)
);


CREATE TABLE ALMACEN (
                ALM_ID INTEGER NOT NULL,
                ALM_UBICACION VARCHAR(80) NOT NULL,
                ALM_ESTADO VARCHAR(1) DEFAULT A NOT NULL,
                CONSTRAINT ALMACEN_PK PRIMARY KEY (ALM_ID)
);


CREATE TABLE DETALLE_MEDICAMENTO (
                DEM_ID INTEGER NOT NULL,
                ALM_ID INTEGER NOT NULL,
                MED_ID INTEGER NOT NULL,
                DEM_PRESENTACION VARCHAR(120) NOT NULL,
                DEM_CANTIDAD_MAXIMA INTEGER DEFAULT 0 NOT NULL,
                DEM_CANTIDAD_MINIMA INTEGER DEFAULT 0 NOT NULL,
                DEM_EN_EXISTENCIA INTEGER DEFAULT 0 NOT NULL,
                DEM_DESCRIPCION VARCHAR(240) NOT NULL,
                DEM_INDICACIONES VARCHAR(240) NOT NULL,
                DEM_VIA_ADMIN_DOSIS VARCHAR(240) NOT NULL,
                DEM_FECHA_ALTA TIMESTAMP NOT NULL,
                DEM_FECHA_CADUCIDAD TIMESTAMP NOT NULL,
                DEM_ESTADO VARCHAR(1) DEFAULT A NOT NULL,
                CONSTRAINT DETALLE_MEDICAMENTO_PK PRIMARY KEY (DEM_ID)
);


INSERT INTO TIPO_USUARIO(TIU_ID, TIU_NOMBRE, TIU_DESCRIP, TIU_ESTADO) VALUES(1, "ADMINISTRADOR", "USUARIO PARA ADMINISTRAR EL SISTEMA", "A");
INSERT INTO TIPO_USUARIO(TIU_ID, TIU_NOMBRE, TIU_DESCRIP, TIU_ESTADO) VALUES(2, "MEDICO", "MEDICO INTERNO DE LA CLINICA", "A");

INSERT INTO USUARIO(USU_ID, TIU_ID, USU_LOGIN, USU_CONTRASENA, USU_ESTADO, USU_FECHA_ALTA, USU_FECHA_VENCIMIENTO, USU_CORREO) 
VALUES(1, 1, "root", "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92", "A", DATE(), DATE(), "root@gmail.com");

INSERT INTO USUARIO(USU_ID, TIU_ID, USU_LOGIN, USU_CONTRASENA, USU_ESTADO, USU_FECHA_ALTA, USU_FECHA_VENCIMIENTO, USU_CORREO) 
VALUES(2, 2, "medico", "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92", "A", DATE(), DATE(), "medico@gmail.com");


